### PR TITLE
LP, Risks, FAQ, Markets page updates

### PR DESCRIPTION
**Pull request by zachdt**
This PR is not ready to merge, but ready for critique.  

TODO BEFORE MERGE ->
There are several known issues that I will continue working on over the rest of the night, the largest being an order card refactor that includes manage options and a better description.   

The current Router loader is too big and replaces the screen, i need to add a loading bar to topbar like github.

Balances and a "Deposit Asset" column need to be added to the LP page.  LP table row order cards still can't be clicked without closing (thought i fixed this...) and the new LP inputs need a spacer.

Positions card needs to be updated with better styles.

Let me know what you think!  (esp. of the new FAQ and risks page)

### CODE REVIEW

**Comment by zachdt** [comment]
still not super jazzed about the liquidity header styles rn, i have a couple cool ideas but i need to think about it

**Comment by Alexangelj** [comment]
Horizontal scroll too large
image

**Comment by Alexangelj** [comment]
Highlight max button on hover, make the number text darker?

image

**Comment by Alexangelj** [comment]
description bugged remember 
image

**Comment by Alexangelj** [comment]
https://github.com/primitivefinance/primitive-interface/issues/444

**Comment by Alexangelj** [comment]
Need a spacer between inputs for adding liquidity to markets with no liquidity
image

**Comment by Alexangelj** [comment]
Remove pool ratio
Fix share units formatting
image

**Comment by Alexangelj** [comment]
image

Try to iterate on this? I think the structure is there but the design is missing, the other parts of the interface are so clean and this is weakest.

**Comment by Alexangelj** [comment]
image

Remove description. 

For only put options, add a line under "Slippage":
- Multiplier <tooltip>Each put has a multiplier of 1/strikePrice, which means a put can be exercised to buy 1 dai. </tooltip>

**Comment by Alexangelj** [comment]
Title gets formatted weird when too lengthy
image

**Comment by Alexangelj** [comment]
When you first click on markets, and click on connect wallet, it will cause the multi-call error because there is "No network".
image

**Comment by zachdt** [comment]
the network issue is known, something to do with how i deal with a null web3 account in the state hooks.

**Comment by Alexangelj** [comment]
Take out bid and ask and just use the ask as "Price", so we have consistency with liquidity view. Also, bid-ask spread is going to be very small most the time.

image

**Comment by Alexangelj** [comment]
Maybe we make this as simple as the yearn interface?
image

add/remove with two inputs

**Comment by zachdt** [comment]
Im forcing the SushiSwap venue in both WETH and SUSHI markets, this may be a mistake but i will correct the venue attribution later.

**Pull request merged**
