### PR TITLE
Feedback Changes from #146

### LINKED ISSUE #146: Feedback on #144 PR Fix/styling branch
Overall styling is better, going in the right direction. Here's some feedback:

## Positions
image

- Long/Short/LP labels should be 0.66 opacity.
- UNI icon should be smaller
- Reduce the line height of UNI Call and $3 12/30/2020

## Market Header
image

- Call/put toggle needs to be left aligned (looks like there is some spacing/margin there?)
- UNI/Uniswap label is not lined up with other labels in the header
- Market header should be kept grey instead of all black (thats my personal feedback)
- No border on the expiring select menu
- Expiring select menu should be: `Expiring ${date}`

## Order Card
image

- Remove spacing between tabs
- Align the title text and button to the edges like so:
- Cursor on the tabs should be made into a pointer
image

## Options Table Row
image

- Checkmark smaller
- Header should not be highlighted on hover

### PR DESCRIPTION
**Pull request by zachdt**
Closes #146 

Completed all tasks outlined in issue except for...

Grey Header [DONE] -  This was only possible in previous versions due to how the market main and sidebar were positioned using grid.  To make any part of the market header background grey again, I would need to add a border and create a card-style component to make it look passable, the fixed flexbox grid prevents the header from being grey in the same way.  This is purely a compromise between correct usage of flex for screen sizes and what I also deem to be slightly better looks.

Icon Sizes - The IconButton component does not seem to be using my corrected icon sizes, not sure the best way to go about this so I am waiting to see if this is truly necessary.

### CODE REVIEW

**Comment by zachdt** [comment]
Moving on to confirming the closure of #147 and #117.   After that, I will be knocking down #104, #103 in another PR.  To end the night, #125 + metamask event listens (network changed -> page refresh for example).

**Comment by zachdt** [comment]
hmm to compensate for going full black, how about using grey[800] in the top bar?  might add the contrast we are looking for

**Comment by Alexangelj** [comment]
Market header needs to be grey

**Comment by zachdt** [comment]
I can make the whole page grey then just make the sidebar black.   this would save a lot of time

**Comment by zachdt** [comment]
That doesn't work very well nvm.  I will find a workaround

**Comment by Alexangelj** [comment]
image

It needs to extend to the entire left of the screen like we had it before, it looked great that way.

image

This is uneven still
image

These need more space, also add a header for that row like an empty button icon or something
image

Not staying in the box
image

**Comment by zachdt** [comment]
Ill make those changes to the position/table, see what I can do to extend the grey background correctly without messing too much with the grid.

**Comment by zachdt** [comment]
Lmk what you think about the latest changes, need to merge this asap.  Going to move onto #117 and #104

**Comment by Alexangelj** [comment]
Feels so much fresher. Few things, can fix later if we really need to:

Border to separate header from rows
image

That should connect rather than have space
image

**Comment by Alexangelj** [comment]
image

The option table row bottom borders should connect with the border on the right

**Comment by zachdt** [comment]
I removed the border underneath the table header because I thought it looked a bit better than having the border ontop of the grey background.  The table issue is something ive been trying to figure out but will require me to re-do a lot of the table component(s).  Going to merge this for now and make an issue related to the Table.

**Comment by Alexangelj** [comment]
Yeah merge now, we can revisit later

**Comment by Alexangelj** [comment]
image

Positions look great btw

**Pull request merged**
